CREATE TABLE [dbo].[Search]
(
	[UserId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Keyword] NVARCHAR(MAX) NOT NULL, 
    [IsDelete] BIT NOT NULL DEFAULT 0,
    [CreatedOn] DATETIME NULL, 
    [CreatedBy] UNIQUEIDENTIFIER NULL
)
