BEGIN
	INSERT INTO Brand (Name, Description)
	VALUES
		(N'Apple', N'Apple Inc. là một tập đoàn công nghệ đa quốc gia của Mỹ có trụ sở chính tại Cupertino, California, chuyên thiết kế, phát triển và bán thiết bị điện tử tiêu dùng, phần mềm máy tính và các dịch vụ trực tuyến.'),
		(N'Samsung', N'Tập đoàn Samsung là một tập đoàn đa quốc gia của Hàn Quốc có tổng hành dinh đặt tại Samsung Town, Seoul. Tập đoàn có nhiều công ty con, hầu hết hoạt động dưới thương hiệu Samsung, là tập đoàn thương mại lớn nhất Hàn Quốc. Samsung được sáng lập bởi Lee Byung-Chul năm 1938, được khởi đầu là một công ty buôn bán nhỏ.'),
		(N'Acer',N'Được thành lập năm 1976, Acer là tập đoàn đa quốc gia về thiết bị điện tử và phần cứng máy tính của Đài Loan. Hiện nay trụ sở chính của Acer đặt tại thành phố Tân Bắc, Đài Loan và tại San Jose, California, Mỹ. Acer đã tiếp cận thị trường Việt Nam với sản phẩm máy tính cá nhân vào năm 1996.'),
		(N'Asus',N'ASUS là công ty thuộc lĩnh vực điện tử tiêu dùng và phần cứng máy tính đa quốc gia, được thành lập vào năm 1989 và có trụ sở tại Đài Loan. Là thương hiệu gaming và bo mạch chủ hàng đầu thế giới, ASUS luôn cam kết sẽ mang đến những sản phẩm thông minh chất lượng nhất cho người dùng ở hiện tại và tương lai.'),
		(N'Google',N'Google LLC (n. đ Công ty TNHH Google) là một công ty công nghệ đa quốc gia của Mỹ, chuyên về các dịch vụ và sản phẩm liên quan đến Internet, bao gồm các công nghệ quảng cáo trực tuyến, công cụ tìm kiếm, điện toán đám mây, phần mềm và phần cứng.'),
		(N'Huawei',N'Huawei là một tập đoàn đa quốc gia được thành lập vào 1987 có trụ sở tại tỉnh Quảng Đông, Trung Quốc. Huawei là một trong những nhà cung cấp thiết bị viễn thông lớn nhất của Trung Quốc và đứng thứ ba thế giới, hãng này cung cấp các hệ thống mạng cho các nhà khai thác điện thoại di động ở 140 quốc gia khác nhau.'),
		(N'OPPO',N'OPPO Electronics Corp (với tên thương hiệu là OPPO - Camera Phone, trước là: OPPO - Smartphone) là nhà sản xuất thiết bị điện tử, điện thoại di động Android Trung Quốc, có trụ sở đặt tại Đông Hoản, Quảng Đông, công ty con của tập đoàn điện tử BBK Electronics. OPPO cung cấp một số sản phẩm chính như máy nghe nhạc MP3, eBook, DVD/Blu-ray và điện thoại thông minh.'),
		(N'Louis Vuitton',N'Công ty Louis Vuitton (được biết đến nhiều hơn dưới tên gọi đơn giản là Louis Vuitton) là một công ty và nhãn hiệu thời trang xa xỉ của Pháp, có trụ sở tại Paris, Pháp. Đây là một ban của công ty cổ phần Pháp LVMH Louis Vuitton Moët Hennessy S.A. Công ty được đặt tên theo tên người sáng lập ra hãng là Louis Vuitton (4 tháng 8 năm 1821-27 tháng 2 năm 1892), người đã thiết kế và sản xuất hành lý như một Malletier trong nửa sau của thế kỷ 19.'),
		(N'Gucci',N'The House of Gucci, hay được biết đến ngắn gọn là Gucci, là một biểu tượng thời trang sở hữu bởi Ý và Pháp, một nhãn hiệu đồ da nổi tiếng. Gucci được thành lập vào năm 1921 bởi Guccio Gucci tại Florence, Toscana. Dưới sự chỉ đạo của Aldo Gucci (con trai của Guccio), Gucci trở thành một thương hiệu nổi tiếng toàn thế giới, một biểu tượng của Dolce Vita của Ý. Các dòng sản phẩm của hãng bao gồm túi xách, đồ may sẵn, giày dép phụ kiện, đồ trang điểm, nước hoa và đồ trang trí nhà cửa.'),
		(N'Hermes',N'Hermès là một công ty thời trang xa xỉ có trụ sở ở Paris, Pháp. Công ty được sáng lập bởi Thierry Hermès vào năm 1837, ngày nay chuyên sản xuất hàng da, phụ kiện thời trang, nước hoa, hàng xa xỉ, và quần áo may sẵn.'),
		(N'Chanel',N'Chanel là tên thông dụng của một hãng thời trang Pháp, đóng tại thủ đô Paris được Coco Chanel (1883 - 1971) sáng lập. Theo Forbes, công ty Chanel thuộc sở hữu của Alain Wertheimer và Gerard Wertheimer, cả hai là cháu của đối tác ban đầu (1924) của Chanel Pierre Wertheimer.'),
		(N'Prada',N'Prada là một nhãn hiệu thời trang của Ý chuyên về các sản phẩm cao cấp cho nam và nữ (giày dép, túi xách, phụ kiện thời trang...), nhãn hiệu Prada được thành lập bởi Mario Prada năm 1913.'),
		(N'Burberry',N'Burberry là một hãng thời trang sang trọng của Anh, phân phối quần áo thể thao độc đáo sang trọng, phụ kiện thời trang, nước hoa, kính mát, và mỹ phẩm.[2] Họa tiết hình sọc vuông đặc trưng của hãng thời trang này đã trở thành một trong những thương hiệu sao chép rộng rãi nhất.'),
		(N'Rolex',N'Rolex với tên gọi chính xác là Rolex SA là một hãng sản xuất đồng hồ Thụy Sỹ với phân khúc từ cao cấp đến xa xỉ và sang trọng. Rolex SA bao gồm hai thương hiệu là Rolex và Montres Tudor SA chuyên thiết kế, sản xuất, phân phối đồng hồ đeo tay dưới thương hiệu Rolex và Tudor.'),
		(N'Tom Ford',N'Thương hiệu đình đám Tom Ford (TF) được sáng lập bởi nhà thiết kế tài năng và nổi tiếng TomFord, một công thần giúp thương hiệu thời trang Gucci vực dậy và trở thành đế chế thời trang.'),
		(N'Balenciaga',N'Balenciaga là thương hiệu thời trang cao cấp của Tây Ban Nha do nhà thiết kế Cristóbal Balenciaga thành lập năm 1919. Công ty hiện thuộc tập đoàn đa quốc gia Kering của Pháp.[1]'),
		(N'Casio',N'Casio Computer Co., Ltd. (カシオ計算機株式会社 Kashio Keisanki Kabushiki-gaisha) là một công ty chế tạo thiết bị điện tử Nhật Bản được thành lập vào năm 1946, có trụ sở đặt tại Tokyo, Nhật Bản. Casio được người ta biết đến nhiều nhất là về các loại sản phẩm như máy tính (calculator), thiết bị âm thanh, PDA, camera, đồng hồ, nhạc cụ.'),
		(N'Dell',N'Dell Inc. là một công ty đa quốc gia của Hoa Kỳ về phát triển và thương mại hóa công nghệ máy tính có trụ sở tại Round Rock, Texas, Hoa Kỳ. Dell được thành lập năm 1984 do chủ quản gia Michael Dell đồng sáng lập. Đây là công ty có thu nhập lớn thứ 28 tại Hoa Kỳ.'),
		(N'Gigabyte',N'Gigabyte Technology Co., Ltd. (GIGABYTE hoặc GIGA-BYTE), là một nhà sản xuất và phân phối các thiết bị phần cứng máy tính của Đài Loan. Khẩu hiệu của hãng là "Upgrage Your Life" - "nâng cấp cuộc sống của bạn".'),
		(N'Microsoft',N'Microsoft là một tập đoàn đa quốc gia của Hoa Kỳ đặt trụ sở chính tại Redmond, Washington; chuyên phát triển, sản xuất, kinh doanh bản quyền phần mềm và hỗ trợ trên diện rộng các sản phẩm và dịch vụ liên quan đến máy tính. Công ty được sáng lập bởi Bill Gates và Paul Allen vào ngày 4 tháng 4 năm 1975. Nếu tính theo doanh thu thì Microsoft là hãng sản xuất phần mềm lớn nhất thế giới.[2] Nó cũng được gọi là "một trong những công ty có giá trị nhất trên thế giới".'),
		(N'Sony',N'Công ty công nghiệp Sony là một tập đoàn đa quốc gia của Nhật Bản, với trụ sở chính nằm tại Minato, Tokyo, Nhật Bản, và là tập đoàn điện tử đứng thứ 5 thế giới với 81,64 tỉ USD (2011). Sony là một trong những công ty hàng đầu thế giới về điện tử, sản xuất tivi, máy ảnh, máy tính xách tay và đồ dân dụng khác'),
		(N'McDonald',N'McDonald là một tập đoàn kinh doanh hệ thống nhà hàng thức ăn nhanh với khoảng 38.695 nhà hàng tại 119 quốc gia[3] phục vụ các sản phẩm mang thương hiệu riêng của tập đoàn cho 43 triệu lượt khách mỗi ngày. Đây là chuỗi nhà hàng thức ăn nhanh lớn nhất trên thế giới. Công ty được thành lập đầu tiên năm 1940 do anh em Richard và Maurice ("Mick & Mack") McDonald. Nền tảng của sự kinh doanh thành công hôm nay là do Ray Kroc mua lại của anh em McDonald và phát triển thành một trong những dự án kinh doanh thức ăn nhanh thành công nhất thế giới.'),
		(N'KFC',N'Kentucky Fried Chicken, thường được biết đến với tên gọi tắt là KFC, là một chuỗi cửa hàng đồ ăn nhanh của Mỹ chuyên về các sản phẩm gà rán có trụ sở đặt tại Louisville, Kentucky. Đây là chuỗi nhà hàng lớn thứ hai thế giới (xếp theo doanh thu) và chỉ đứng sau McDonald với tổng cộng gần 20.000 nhà hàng tại 123 quốc gia và vùng lãnh thổ (tính đến tháng 12 năm 2015). Đây là một trong những thương hiệu trực thuộc Yum! Brands, một tập đoàn cũng sở hữu chuỗi nhà hàng Pizza Hut và Taco Bell.'),
		(N'StarBucks',N'Starbucks là một thương hiệu cà phê nổi tiếng trên thế giới. Hãng cà phê Starbucks có trụ sở chính ở Seattle, Washington, Hoa Kỳ; ngoài ra, hãng có hơn 23.000 quán ở 64 quốc gia.'),
		(N'LG',N'LG là một tập đoàn công nghiệp nặng đa quốc gia của Hàn Quốc có trụ sở chính được đặt tại thành phố Seoul. Các sản phẩm của tập đoàn này bao gồm: điện tử tiêu dùng, thiết bị viễn thông, điện thoại thông minh (nhưng đã khai tử từ năm 2021)[2], chất bán dẫn, Pin và các sản phẩm từ hóa chất,... '),
		(N'Vinamilk',N'Công ty Cổ phần Sữa Việt Nam (tên tiếng Anh là Vietnam Dairy Products Joint Stock Company); tên khác: Vinamilk; mã chứng khoán HOSE: VNM, là một công ty sản xuất, kinh doanh sữa và sản phẩm từ sữa cũng như các thiết bị máy móc liên quan tại Việt Nam.')

END